[project]
name = "udemy-python-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "requests>=2.32.3",
    "ruff>=0.11.8",
    "websocket-client>=1.8.0",
]
